name: dm_model
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - tqdm
  - ipywidgets
  - fastparquet
  - pyarrow
  - scipy
  - scikit-learn
  - statsmodels
  - catboost
  - xgboost
  - matplotlib
  - seaborn
  - shapely
  - pip:
      - accessible-space>=2.0.15,<3
      - rdp
      - kloppy
      - socceraction
      - pandera
      - multimethod<2
