from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE_FEATURE_DIR = "data/ajax/features/action_graphs"
BASE_LABEL_DIR = "data/ajax/features/action_labels_disc_0.9"
INTENT_TRAIN_FEATURE_DIR = "data/ajax/features/action_graphs_intent_train"
INTENT_TRAIN_LABEL_DIR = "data/ajax/features/action_labels_intent_train_disc_0.9"

TRAINING_COMMANDS: list[list[str]] = [
    [
        "--task",
        "pass_intent",
        "--trial",
        "20",
        "--model",
        "gat",
        "--min_pass_dur",
        "0.5",
        "--possessor_aware",
        "--keeper_aware",
        "--ball_z_aware",
        "--poss_vel_aware",
        "--extend_features",
        "--sparsify",
        "none",
        "--node_emb_dim",
        "128",
        "--graph_emb_dim",
        "128",
        "--mlp_h1_dim",
        "64",
        "--mlp_h2_dim",
        "16",
        "--gnn_layers",
        "2",
        "--gnn_heads",
        "4",
        "--skip_conn",
        "--n_epochs",
        "100",
        "--batch_size",
        "512",
        "--lambda_l1",
        "0.0001",
        "--start_lr",
        "0.002",
        "--min_lr",
        "1e-5",
        "--print_freq",
        "50",
        "--seed",
        "100",
        "--feature_dir",
        BASE_FEATURE_DIR,
        "--label_dir",
        BASE_LABEL_DIR,
        "--train_feature_dir",
        INTENT_TRAIN_FEATURE_DIR,
        "--train_label_dir",
        INTENT_TRAIN_LABEL_DIR,
    ],
    [
        "--task",
        "action_intent",
        "--trial",
        "0",
        "--model",
        "gat",
        "--min_pass_dur",
        "0.5",
        "--possessor_aware",
        "--keeper_aware",
        "--ball_z_aware",
        "--poss_vel_aware",
        "--extend_features",
        "--sparsify",
        "none",
        "--edge_in_dim",
        "2",
        "--node_emb_dim",
        "128",
        "--graph_emb_dim",
        "128",
        "--mlp_h1_dim",
        "64",
        "--mlp_h2_dim",
        "16",
        "--gnn_layers",
        "2",
        "--gnn_heads",
        "4",
        "--skip_conn",
        "--n_epochs",
        "100",
        "--batch_size",
        "512",
        "--lambda_l1",
        "0.0001",
        "--start_lr",
        "0.002",
        "--min_lr",
        "1e-5",
        "--print_freq",
        "50",
        "--seed",
        "100",
        "--feature_dir",
        BASE_FEATURE_DIR,
        "--label_dir",
        BASE_LABEL_DIR,
        "--train_feature_dir",
        INTENT_TRAIN_FEATURE_DIR,
        "--train_label_dir",
        INTENT_TRAIN_LABEL_DIR,
    ],
    [
        "--task",
        "pass_success",
        "--trial",
        "20",
        "--model",
        "gat",
        "--ipw_model_id",
        "pass_intent/20",
        "--min_pass_dur",
        "0.5",
        "--possessor_aware",
        "--keeper_aware",
        "--ball_z_aware",
        "--poss_vel_aware",
        "--extend_features",
        "--sparsify",
        "none",
        "--node_emb_dim",
        "128",
        "--graph_emb_dim",
        "128",
        "--mlp_h1_dim",
        "64",
        "--mlp_h2_dim",
        "16",
        "--gnn_layers",
        "2",
        "--gnn_heads",
        "4",
        "--skip_conn",
        "--n_epochs",
        "100",
        "--batch_size",
        "512",
        "--lambda_l1",
        "0.0001",
        "--start_lr",
        "0.002",
        "--min_lr",
        "1e-5",
        "--print_freq",
        "50",
        "--seed",
        "100",
        "--feature_dir",
        BASE_FEATURE_DIR,
        "--label_dir",
        BASE_LABEL_DIR,
    ],
    [
        "--task",
        "outcome_scoring",
        "--trial",
        "20",
        "--model",
        "gat",
        "--keeper_aware",
        "--use_xg",
        "--return_type",
        "disc_0.9",
        "--sparsify",
        "none",
        "--edge_in_dim",
        "2",
        "--node_emb_dim",
        "128",
        "--graph_emb_dim",
        "128",
        "--mlp_h1_dim",
        "64",
        "--mlp_h2_dim",
        "16",
        "--gnn_layers",
        "2",
        "--gnn_heads",
        "4",
        "--skip_conn",
        "--n_epochs",
        "100",
        "--batch_size",
        "512",
        "--lambda_l1",
        "1e-6",
        "--start_lr",
        "0.0002",
        "--min_lr",
        "1e-5",
        "--print_freq",
        "50",
        "--seed",
        "100",
        "--feature_dir",
        BASE_FEATURE_DIR,
        "--label_dir",
        BASE_LABEL_DIR,
    ],
    [
        "--task",
        "outcome_conceding",
        "--trial",
        "20",
        "--model",
        "gat",
        "--keeper_aware",
        "--use_xg",
        "--return_type",
        "disc_0.9",
        "--sparsify",
        "none",
        "--edge_in_dim",
        "2",
        "--node_emb_dim",
        "128",
        "--graph_emb_dim",
        "128",
        "--mlp_h1_dim",
        "64",
        "--mlp_h2_dim",
        "16",
        "--gnn_layers",
        "2",
        "--gnn_heads",
        "4",
        "--skip_conn",
        "--n_epochs",
        "100",
        "--batch_size",
        "512",
        "--lambda_l1",
        "1e-6",
        "--start_lr",
        "0.0002",
        "--min_lr",
        "1e-5",
        "--print_freq",
        "50",
        "--seed",
        "100",
        "--feature_dir",
        BASE_FEATURE_DIR,
        "--label_dir",
        BASE_LABEL_DIR,
    ],
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--use_xt", action="store_true", help="Train outcome models with xT targets instead of xG.")
    return parser.parse_args()


def configure_command(args: list[str], use_xt: bool) -> list[str]:
    configured = list(args)
    if not use_xt or configured[1] not in {"outcome_scoring", "outcome_conceding"}:
        return configured

    configured = [arg for arg in configured if arg != "--use_xg"]
    if "--use_xt" not in configured:
        insert_at = configured.index("--return_type") if "--return_type" in configured else len(configured)
        configured.insert(insert_at, "--use_xt")
    return configured


def main() -> None:
    cli_args = parse_args()
    python = sys.executable
    for args in TRAINING_COMMANDS:
        command = [python, "train.py", *configure_command(args, cli_args.use_xt)]
        print("Running:", " ".join(command))
        subprocess.run(command, cwd=ROOT, check=True)


if __name__ == "__main__":
    main()
